const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=process.env.TEST_URL||'http://127.0.0.1:8766/';
for(const width of [320,390,768,1400]){await p.setViewportSize({width,height:1000});await p.goto(url+'?qa='+Date.now()+'#rainbow-unicorns');await p.waitForFunction(()=>typeof data!=='undefined'&&data?.soccerProjections);await p.locator('#tab-rainbow-unicorns').click();assert.ok(await p.locator('#rainbow-unicorns').isVisible());await p.waitForFunction(()=>document.querySelectorAll('.rainbow-line').length===2&&document.querySelector('.rainbow-line').textContent.includes('Model ·'));assert.equal(await p.locator('.rainbow-fixture').count(),2);assert.equal(await p.locator('.sports').isVisible(),false);
const checks=await p.evaluate(()=>{const actual=[...document.querySelectorAll('.rainbow-fixture')];return SBMSARainbow.nextTwo(data.divisions).map((g,i)=>{const id=['fall-2026','5ug','Boxx',g.home,g.away,g.start_iso],f=data.soccerProjections.forecasts.find(f=>JSON.stringify(f.fixture_id)===JSON.stringify(id));return {start:actual[i].dataset.start,expected:g.start_iso,line:actual[i].querySelector('.rainbow-line').textContent,expectedLine:'Model · '+SBMSARainbow.line(f,g.home,g.away),text:actual[i].textContent,gp:[f.home_gp,f.away_gp],links:actual[i].querySelectorAll('a').length};});});for(const c of checks){assert.equal(c.start,c.expected);assert.equal(c.line,c.expectedLine);assert.ok(c.text.includes('Coach'));assert.equal(c.links,2);}assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(process.env.QA_DIR||'/tmp',`rainbow-${width}.png`),fullPage:true});
await p.locator('#tab-rankings').click();for(const sport of ['flag','8u','6u','5ug']){await p.locator(`[data-sport="${sport}"]`).click();for(const mode of ['raw','capped']){await p.locator('#'+mode).click();const expected=await p.evaluate(()=>SBMSARatings.compute(data.divisions,sport,mode).map(t=>[t.team,String(t.rank||'')]));assert.deepEqual(await p.locator('#rows .row').evaluateAll(es=>es.map(e=>[e.dataset.team,e.dataset.rank])),expected);}
if(sport==='5ug'){assert.equal(await p.locator('#rows .favorite').count(),1);assert.equal(await p.locator('#rows .favorite').getAttribute('data-team'),'Rainbow Unicorns');assert.ok((await p.locator('#rows .favorite .division').innerText()).includes('Boxx'));assert.equal(await p.locator('#rows .favorite [aria-label="Followed team"]').count(),1);assert.equal(await p.locator('#rows .favorite').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(244, 231, 223)');assert.equal(await p.locator('#focus').isVisible(),false);assert.deepEqual(await p.locator('#division option').allTextContents(),['All divisions','Akers','Boxx']);}
await p.locator('#tab-advanced').click();for(const sort of ['board','raw_total','raw_margin','scored_pg','allowed_pg','adjusted_margin','sos']){await p.locator('#stat-sort').selectOption(sort);assert.ok(await p.evaluate(()=>{let values=[...document.querySelectorAll('#stats-body tr')].map(e=>e.dataset.metric).filter(v=>v!=='').map(Number);return values.every((v,i)=>i===0||(document.querySelector('#stat-sort').value==='allowed_pg'||document.querySelector('#stat-sort').value==='board'?v>=values[i-1]:v<=values[i-1]));}));}assert.ok((await p.locator('#stats-head').innerText()).includes(sport==='flag'?'PF/G':'GF/G'));
await p.locator('#tab-league-schedule').click();for(const div of await p.locator('#division option').evaluateAll(es=>es.map(e=>e.value))){await p.locator('#division').selectOption(div);for(const filter of ['All','Results','Upcoming']){await p.locator(`[data-league-filter="${filter}"]`).click();const n=await p.evaluate(({sport,div,filter})=>SBMSALeagueSchedule.filterRows(SBMSALeagueSchedule.buildRows(data,sport),{division:div,filter}).length,{sport,div,filter});assert.equal(await p.locator('[data-league-fixture]').count(),n);}if(sport==='5ug')assert.equal(await p.locator('[data-league-projections]').count(),0);}await p.locator('#division').selectOption('all');await p.locator('#tab-rankings').click();}
await p.locator('#tab-team-schedules').click();assert.equal(await p.locator('#team-schedules').getByText('Rainbow Unicorns',{exact:true}).count(),0);
}
assert.deepEqual(errors,[]);console.log('PASS all four leagues, modes, advanced sorts, divisions/status counts, dedicated next two, links, no family association, widths 320/390/768/1400; zero JS errors');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
